name: CI

on:
  push:
    branches:
      - main  
    paths:
      - 'project/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute tests
      run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh