name: Project Tests

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'data/**'
      - 'project/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Code
        uses: actions/checkout@v2
      
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytest requests sqlalchemy pyexcel_ods scikit-learn xlrd

        

      - name: Execute tests.sh
        run: |
          chmod u+r+x ./project/tests.sh
          cd ./project
          ./tests.sh
